export const countries = [
	{ gl: "DZ", name: "Algeria" },
	{ gl: "AR", name: "Argentina" },
	{ gl: "AU", name: "Australia" },
	{ gl: "AT", name: "Austria" },
	{ gl: "AZ", name: "Azerbaijan" },
	{ gl: "BH", name: "Bahrain" },
	{ gl: "BD", name: "Bangladesh" },
	{ gl: "BY", name: "Belarus" },
	{ gl: "BE", name: "Belgium" },
	{ gl: "BO", name: "Bolivia" },
	{ gl: "BA", name: "Bosnia and Herzegovina" },
	{ gl: "BR", name: "Brazil" },
	{ gl: "BG", name: "Bulgaria" },
	{ gl: "KH", name: "Cambodia" },
	{ gl: "CA", name: "Canada" },
	{ gl: "CL", name: "Chile" },
	{ gl: "CO", name: "Colombia" },
	{ gl: "CR", name: "Costa Rica" },
	{ gl: "HR", name: "Croatia" },
	{ gl: "CY", name: "Cyprus" },
	{ gl: "CZ", name: "Czechia" },
	{ gl: "DK", name: "Denmark" },
	{ gl: "DO", name: "Dominican Republic" },
	{ gl: "EC", name: "Ecuador" },
	{ gl: "EG", name: "Egypt" },
	{ gl: "SV", name: "El Savador" },
	{ gl: "EE", name: "Estonia" },
	{ gl: "FI", name: "Finland" },
	{ gl: "FR", name: "France" },
	{ gl: "GE", name: "Georgia" },
	{ gl: "DE", name: "Germany" },
	{ gl: "GH", name: "Ghana" },
	{ gl: "GR", name: "Greece" },
	{ gl: "GT", name: "Guatemala" },
	{ gl: "HN", name: "Honduras" },
	{ gl: "HK", name: "Hong Kong" },
	{ gl: "HU", name: "Hungary" },
	{ gl: "IS", name: "Iceland" },
	{ gl: "IN", name: "India" },
	{ gl: "ID", name: "Indonesia" },
	{ gl: "IQ", name: "Iraq" },
	{ gl: "IE", name: "Ireland" },
	{ gl: "IL", name: "Israel" },
	{ gl: "IT", name: "Italy" },
	{ gl: "JM", name: "Jamaica" },
	{ gl: "JP", name: "Japan" },
	{ gl: "JO", name: "Jordan" },
	{ gl: "KZ", name: "Kazakhstan" },
	{ gl: "KE", name: "Kenya" },
	{ gl: "KW", name: "Kuwait" },
	{ gl: "LA", name: "Laos" },
	{ gl: "LV", name: "Latvia" },
	{ gl: "LB", name: "Lebanon" },
	{ gl: "LY", name: "Libya" },
	{ gl: "LI", name: "Liechtenstein" },
	{ gl: "LT", name: "Lithuania" },
	{ gl: "LU", name: "Luxembourg" },
	{ gl: "MY", name: "Malaysia" },
	{ gl: "MT", name: "Malta" },
	{ gl: "MX", name: "Mexico" },
	{ gl: "ME", name: "Montenegro" },
	{ gl: "MA", name: "Morocco" },
	{ gl: "NP", name: "Nepal" },
	{ gl: "NL", name: "Netherlands" },
	{ gl: "NZ", name: "New Zealand" },
	{ gl: "NI", name: "Nicaragua" },
	{ gl: "NG", name: "Nigeria" },
	{ gl: "MK", name: "North Macedonia" },
	{ gl: "NO", name: "Norway" },
	{ gl: "OM", name: "Oman" },
	{ gl: "PK", name: "Pakistan" },
	{ gl: "PA", name: "Panama" },
	{ gl: "PG", name: "Papua New Guinea" },
	{ gl: "PY", name: "Paraguay" },
	{ gl: "PE", name: "Peru" },
	{ gl: "PH", name: "Philippines" },
	{ gl: "PL", name: "Poland" },
	{ gl: "PR", name: "Puerto Rico" },
	{ gl: "QA", name: "Qatar" },
	{ gl: "RO", name: "Romania" },
	{ gl: "RU", name: "Russia" },
	{ gl: "SA", name: "Saudi Arabia" },
	{ gl: "SN", name: "Senegal" },
	{ gl: "RS", name: "Serbia" },
	{ gl: "SG", name: "Singapore" },
	{ gl: "SK", name: "Slovakia" },
	{ gl: "SI", name: "Slovenia" },
	{ gl: "ZA", name: "South Africa" },
	{ gl: "KR", name: "South Korea" },
	{ gl: "ES", name: "Spain" },
	{ gl: "LK", name: "Sri Lanka" },
	{ gl: "SE", name: "Sweden" },
	{ gl: "CH", name: "Switzerland" },
	{ gl: "TW", name: "Taiwan" },
	{ gl: "TH", name: "Thailand" },
	{ gl: "TN", name: "Tunisia" },
	{ gl: "TR", name: "Turkey" },
	{ gl: "UG", name: "Uganda" },
	{ gl: "UA", name: "Ukraine" },
	{ gl: "AE", name: "United Arab Emirates" },
	{ gl: "GB", name: "United Kingdom" },
	{ gl: "US", name: "United States" },
	{ gl: "UY", name: "Uruguay" },
	{ gl: "VE", name: "Venezuela" },
	{ gl: "VN", name: "Vietnam" },
	{ gl: "YE", name: "Yemen" },
	{ gl: "ZW", name: "Zimbabwe" },
];